import { LanguageDictionary } from './types';

// Hardcoded holidays for demonstration. In a real app, this might come from an API or a larger JSON file.
// Format: 'MM-DD': 'Holiday Name' (Year agnostic for simplicity in this demo, though movable holidays like Easter require calculation)
export const HOLIDAYS_DB: { [countryCode: string]: { [date: string]: string } } = {
  PT: {
    '01-01': 'Ano Novo',
    '04-25': 'Dia da Liberdade',
    '05-01': 'Dia do Trabalhador',
    '06-10': 'Dia de Portugal',
    '08-15': 'Assunção de Nossa Senhora',
    '10-05': 'Implantação da República',
    '11-01': 'Dia de Todos os Santos',
    '12-01': 'Restauração da Independência',
    '12-08': 'Imaculada Conceição',
    '12-25': 'Natal'
  },
  BR: {
    '01-01': 'Confraternização Universal',
    '04-21': 'Tiradentes',
    '05-01': 'Dia do Trabalho',
    '09-07': 'Independência do Brasil',
    '10-12': 'Nossa Senhora Aparecida',
    '11-02': 'Finados',
    '11-15': 'Proclamação da República',
    '11-20': 'Dia da Consciência Negra',
    '12-25': 'Natal'
  },
  US: {
    '01-01': 'New Year\'s Day',
    '07-04': 'Independence Day',
    '11-11': 'Veterans Day',
    '12-25': 'Christmas Day'
  },
  ES: {
    '01-01': 'Año Nuevo',
    '01-06': 'Epifanía del Señor',
    '05-01': 'Fiesta del Trabajo',
    '08-15': 'Asunción de la Virgen',
    '10-12': 'Fiesta Nacional de España',
    '11-01': 'Todos los Santos',
    '12-06': 'Día de la Constitución',
    '12-08': 'Inmaculada Concepción',
    '12-25': 'Natividad del Señor'
  },
  FR: {
    '01-01': 'Jour de l\'an',
    '05-01': 'Fête du Travail',
    '05-08': 'Victoire 1945',
    '07-14': 'Fête Nationale',
    '08-15': 'Assomption',
    '11-01': 'Toussaint',
    '11-11': 'Armistice 1918',
    '12-25': 'Noël'
  }
};

export const COUNTRIES = [
  { code: 'PT', name: 'Portugal' },
  { code: 'BR', name: 'Brasil' },
  { code: 'US', name: 'United States' },
  { code: 'ES', name: 'España' },
  { code: 'FR', name: 'France' },
  { code: 'DE', name: 'Deutschland' },
  { code: 'IT', name: 'Italia' },
  { code: 'NL', name: 'Nederland' },
];

export const MOTIVATIONAL_QUOTES: { [key: string]: string[] } = {
  pt: [
    "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
    "Acredite que você pode, assim você já está no meio do caminho.",
    "Seu trabalho vai preencher uma grande parte da sua vida, a única maneira de estar verdadeiramente satisfeito é fazer o que você acredita ser um ótimo trabalho.",
    "A persistência é o caminho do êxito.",
    "Hoje é um dia perfeito para começar a concretizar seus sonhos."
  ],
  "pt-BR": [
    "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
    "Acredite que você pode, assim você já está no meio do caminho.",
    "O único lugar onde o sucesso vem antes do trabalho é no dicionário.",
    "A persistência realiza o impossível.",
    "Hoje é um dia perfeito para começar a concretizar seus sonhos."
  ],
  en: [
    "Success is the sum of small efforts, repeated day in and day out.",
    "Believe you can and you're halfway there.",
    "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
    "Persistence is the path to success.",
    "Today is a perfect day to start making your dreams come true."
  ],
  es: [
    "El éxito es la suma de pequeños esfuerzos repetidos día tras día.",
    "Cree que puedes y ya estarás a medio camino.",
    "Tu trabajo va a llenar gran parte de tu vida, la única forma de estar realmente satisfecho es hacer lo que crees que es un gran trabajo.",
    "La persistencia es el camino del éxito.",
    "Hoy es un día perfecto para empezar a hacer realidad tus sueños."
  ],
  fr: [
    "Le succès est la somme de petits efforts, répétés jour après jour.",
    "Croyez que vous pouvez et vous êtes à mi-chemin.",
    "Votre travail va remplir une grande partie de votre vie, la seule façon d'être vraiment satisfait est de faire ce que vous croyez être un excellent travail.",
    "La persévérance est la voie du succès.",
    "Aujourd'hui est un jour parfait pour commencer à réaliser vos rêves."
  ],
  it: [
    "Il successo è la somma di piccoli sforzi, ripetuti giorno dopo giorno.",
    "Credi di potercela fare e sei già a metà strada.",
    "L'unico modo per fare un ottimo lavoro è amare quello che fai.",
    "La perseveranza è la chiave del successo.",
    "Oggi è il giorno perfetto per iniziare a realizzare i tuoi sogni."
  ],
  de: [
    "Erfolg ist die Summe kleiner Anstrengungen, die jeden Tag wiederholt werden.",
    "Glaube daran, dass du es kannst, und du hast schon den halben Weg geschafft.",
    "Der einzige Weg, großartige Arbeit zu leisten, ist zu lieben, was man tut.",
    "Ausdauer ist der Schlüssel zum Erfolg.",
    "Heute ist der perfekte Tag, um deine Träume zu verwirklichen."
  ],
  nl: [
    "Succes is de som van kleine inspanningen, dag in dag uit herhaald.",
    "Geloof dat je het kunt en je bent al halverwege.",
    "De enige manier om geweldig werk te leveren, is houden van wat je doet.",
    "Doorzettingsvermogen is de weg naar succes.",
    "Vandaag is een perfecte dag om je dromen waar te maken."
  ],
  ga: [
    "Is é an rath suim na n-iarrachtaí beaga, a dhéantar arís agus arís eile lá i ndiaidh lae.",
    "Creid gur féidir leat agus tá an leath bealaigh déanta agat.",
    "Is é an t-aon bhealach chun obair iontach a dhéanamh ná grá a bheith agat don rud a dhéanann tú.",
    "Is í an bhuanseasmhacht cosán an ratha.",
    "Is lá foirfe é inniu chun do bhrionglóidí a fhíorú."
  ],
  hi: [
    "सफलता छोटे-छोटे प्रयासों का योग है, जिन्हें दिन-रात दोहराया जाता है।",
    "विश्वास करो कि तुम कर सकते हो और तुम आधे रास्ते पर हो।",
    "महान कार्य करने का एकमात्र तरीका यह है कि आप जो करते हैं उससे प्यार करें।",
    "दृढ़ता सफलता की कुंजी है।",
    "आज का दिन अपने सपनों को साकार करने के लिए एकदम सही है।"
  ],
  ur: [
    "کامیابی چھوٹی چھوٹی کوششوں کا مجموعہ ہے، جو دن رات دہرائی جاتی ہیں۔",
    "یقین رکھیں کہ آپ کر سکتے ہیں اور آپ آدھے راستے پر ہیں۔",
    "عظیم کام کرنے کا واحد طریقہ یہ ہے کہ آپ جو کرتے ہیں اس سے محبت کریں۔",
    "استقامت کامیابی کا راستہ ہے۔",
    "آج کا دن اپنے خوابوں کو شرمندہ تعبیر کرنے کے لیے بہترین ہے۔"
  ],
  ar: [
    "النجاح هو محصلة اجتهادات صغيرة تتراكم يوماً بعد يوم.",
    "آمن بأنك تستطيع، وستكون قد قطعت نصف الطريق.",
    "الطريقة الوحيدة للقيام بعمل عظيم هي أن تحب ما تعمل.",
    "المثابرة هي طريق النجاح.",
    "اليوم هو يوم مثالي للبدء في تحقيق أحلامك."
  ]
};

// System Instruction for the Help Bot
export const APP_SYSTEM_INSTRUCTION = `
You are "Axis", the intelligent support assistant for the "Digital Nexus TimeKeeper" application.
Your goal is to help users understand how to use the app.
Be concise, friendly, and helpful. Use the user's language.

Here is the knowledge base of the app features:

1. **Dashboard (Home)**: 
   - Displays a calendar view of the current month.
   - Click on any day to add or edit a time record.
   - In the modal, you can set Start Time, End Time, Lunch Duration, mark as Absent, or add Advances (Vales).
   - You can also specify the Work Site/Location and add Observations.
   - Shows a motivational quote daily.
   - Indicates status with colors: Green (8h+), Yellow (<8h), Red (Absent), Purple (Holiday).
   - Use arrows to navigate between months.

2. **Reports**:
   - Shows statistics: Total Hours, Days Worked, Gross Earnings, Advances, Deductions (SS/IRS), and Net Payout.
   - Allows exporting data to PDF and Excel (includes location and notes).
   - Displays a bar chart of hours worked per day.
   - Use arrows to view reports for previous/next months.

3. **Profile**:
   - Edit hourly rate, currency.
   - Configure Social Security and IRS deductions (Percentage or Fixed Value).
   - Upload a profile photo or configure a generated avatar.
   - Backup your individual data.

4. **Chat**:
   - Communicate with other users or the Master admin.
   - Messages are auto-translated.

5. **Admin (Master Only)**:
   - Create, Edit, and Delete user accounts (subscriptions).
   - Reset passwords.
   - Search for users.
   - Perform full system backup.

6. **General**:
   - Multi-language support.
   - Holiday detection based on selected country in profile.

If the user asks something you cannot answer based on this info, or if they seem frustrated, kindly suggest they click the "Contact Support" button to escalate to a human.
`;

export const TRANSLATIONS: LanguageDictionary = {
  pt: {
    welcome: "Bem-vindo",
    goodMorning: "Bom dia",
    goodAfternoon: "Boa tarde",
    goodEvening: "Boa noite",
    login: "Entrar",
    username: "Utilizador",
    password: "Password",
    dashboard: "Início",
    reports: "Relatórios",
    profile: "Perfil",
    chat: "Chat / Network",
    help: "Ajuda",
    settings: "Definições",
    logout: "Sair",
    clockIn: "Registar Entrada",
    clockOut: "Registar Saída",
    date: "Data",
    startTime: "Hora Início",
    endTime: "Hora Fim",
    lunch: "Almoço (min)",
    notes: "Observações",
    save: "Guardar",
    cancel: "Cancelar",
    absent: "Marcar Falta",
    present: "Presente",
    totalHours: "Total de Horas",
    expectedHours: "Horas Esperadas",
    balance: "Saldo",
    exportPDF: "Exportar PDF",
    exportExcel: "Exportar Excel",
    mon: "Seg",
    tue: "Ter",
    wed: "Qua",
    thu: "Qui",
    fri: "Sex",
    sat: "Sáb",
    sun: "Dom",
    hoursWorked: "Horas Trabalhadas",
    dailyGoal: "Meta Diária (8h)",
    status: "Estado",
    editRecord: "Editar Registo",
    companyName: "Digital Nexus Solutions",
    adminDashboard: "Gestão de Assinaturas",
    activeSubscriptions: "Assinaturas Ativas",
    newSubscription: "Nova Assinatura",
    fullName: "Nome Completo",
    nif: "NIF",
    email: "Email",
    phone: "Telefone",
    hourlyRate: "Valor Hora",
    createAccount: "Criar Conta",
    noUsers: "Nenhum utilizador registado.",
    id: "ID",
    actions: "Ações",
    editUser: "Editar Utilizador",
    deleteUser: "Excluir",
    confirmDelete: "Tem a certeza que deseja excluir este utilizador?",
    generatedId: "ID Gerado",
    changePassword: "Alterar Password",
    newPassword: "Nova Password",
    confirmPassword: "Confirmar Password",
    passwordMismatch: "As passwords não coincidem",
    provisionalPasswordNotice: "Está a usar uma password provisória. Por favor, defina uma nova.",
    resetPassword: "Resetar Password (123)",
    passwordResetSuccess: "Password resetada para '123' com sucesso.",
    socialSecurity: "Segurança Social",
    irs: "IRS (Imposto)",
    socialSecurityManual: "Seg. Social (Manual)",
    advance: "Vale",
    advancesReceived: "Vales Recebidos",
    totalAdvances: "Total Vales",
    deductionType: "Tipo de Desconto",
    percentage: "Percentagem (%)",
    fixedValue: "Valor Fixo",
    value: "Valor",
    netEarnings: "Ganhos Líquidos",
    grossEarnings: "Ganhos Brutos",
    profileSettings: "Definições de Perfil",
    updateProfile: "Atualizar Perfil",
    profileUpdated: "Perfil atualizado com sucesso!",
    uploadPhoto: "Carregar Foto",
    removePhoto: "Remover Foto",
    photoDescription: "Carregue uma foto sua para personalizar o perfil.",
    typeMessage: "Escreva uma mensagem...",
    send: "Enviar",
    noMessages: "Nenhuma mensagem ainda. Diga olá!",
    country: "País",
    holiday: "Feriado",
    totalDays: "Dias Trabalhados",
    helpTitle: "Como podemos ajudar?",
    helpSubtitle: "Pergunte ao Axis, nosso Assistente Digital",
    contactSupport: "Contactar Suporte Humano",
    botPlaceholder: "Ex: Como exporto para PDF?",
    ticketCreated: "O seu pedido foi enviado para o suporte técnico. Entraremos em contacto brevemente.",
    botName: "Axis",
    helpWelcome: "Olá! Sou o Axis, o seu assistente. Pode escrever no seu idioma — eu compreendo todos. Em que posso ajudar?",
    joinDiscount: "Quero aderir com DESCONTO!",
    alreadyActive: "Já ativei minha conta! Quero fazer Login",
    salesPageTitle: "Ative sua conta Digital Nexus",
    planMonthly: "Plano Mensal - Acesso Total",
    paymentMethod: "Método de Pagamento",
    mbway: "MBWAY",
    creditCard: "Cartão de Crédito",
    cardNumber: "Número do Cartão",
    expiryDate: "Validade (MM/AA)",
    cvv: "CVV",
    payAndActivate: "Pagar e Ativar Conta",
    processingPayment: "Processando pagamento...",
    paymentSuccess: "Pagamento confirmado! A sua conta foi criada.",
    mbwayNumber: "Número de Telemóvel MBWAY",
    planYearly: "Apenas 1 pagamento por ano",
    unlimitedAccess: "Acesso ILIMITADO",
    memberChat: "Chat entre membros",
    continueToPayment: "Continuar para Pagamento",
    back: "Voltar",
    limitedOfferApplied: "OFERTA LIMITADA aplicada",
    totalToday: "Total Hoje",
    perYear: "/ano",
    exportFeatures: "Exportar PDF/Excel",
    support247: "Suporte 24h/7",
    backupData: "Backup de Dados",
    backupSuccess: "Backup descarregado com sucesso!",
    restoreBackup: "Restaurar Backup",
    restoreSuccess: "Dados restaurados com sucesso!",
    invalidBackupFile: "Arquivo de backup inválido.",
    workSite: "Local/Serviço",
    observations: "Observações"
  },
  "pt-BR": {
    welcome: "Bem-vindo",
    goodMorning: "Bom dia",
    goodAfternoon: "Boa tarde",
    goodEvening: "Boa noite",
    login: "Entrar",
    username: "Usuário",
    password: "Senha",
    dashboard: "Início",
    reports: "Relatórios",
    profile: "Perfil",
    chat: "Chat / Network",
    help: "Ajuda",
    settings: "Configurações",
    logout: "Sair",
    clockIn: "Registrar Entrada",
    clockOut: "Registrar Saída",
    date: "Data",
    startTime: "Hora Início",
    endTime: "Hora Fim",
    lunch: "Almoço (min)",
    notes: "Observações",
    save: "Salvar",
    cancel: "Cancelar",
    absent: "Marcar Falta",
    present: "Presente",
    totalHours: "Total de Horas",
    expectedHours: "Horas Esperadas",
    balance: "Saldo",
    exportPDF: "Exportar PDF",
    exportExcel: "Exportar Excel",
    mon: "Seg",
    tue: "Ter",
    wed: "Qua",
    thu: "Qui",
    fri: "Sex",
    sat: "Sáb",
    sun: "Dom",
    hoursWorked: "Horas Trabalhadas",
    dailyGoal: "Meta Diária (8h)",
    status: "Status",
    editRecord: "Editar Registro",
    companyName: "Digital Nexus Solutions",
    adminDashboard: "Gestão de Assinaturas",
    activeSubscriptions: "Assinaturas Ativas",
    newSubscription: "Nova Assinatura",
    fullName: "Nome Completo",
    nif: "CPF/CNPJ",
    email: "E-mail",
    phone: "Telefone",
    hourlyRate: "Valor Hora",
    createAccount: "Criar Conta",
    noUsers: "Nenhum usuário cadastrado.",
    id: "ID",
    actions: "Ações",
    editUser: "Editar Usuário",
    deleteUser: "Excluir",
    confirmDelete: "Tem certeza que deseja excluir este usuário?",
    generatedId: "ID Gerado",
    changePassword: "Alterar Senha",
    newPassword: "Nova Senha",
    confirmPassword: "Confirmar Senha",
    passwordMismatch: "As senhas não coincidem",
    provisionalPasswordNotice: "Você está usando uma senha provisória. Por favor, defina uma nova senha.",
    resetPassword: "Resetar Senha (123)",
    passwordResetSuccess: "Senha resetada para '123' com sucesso.",
    socialSecurity: "Previdência Social (INSS)",
    irs: "Imposto de Renda (IRRF)",
    socialSecurityManual: "INSS (Manual)",
    advance: "Vale/Adiantamento",
    advancesReceived: "Vales Recebidos",
    totalAdvances: "Total Vales",
    deductionType: "Tipo de Desconto",
    percentage: "Porcentagem (%)",
    fixedValue: "Valor Fixo",
    value: "Valor",
    netEarnings: "Salário Líquido",
    grossEarnings: "Salário Bruto",
    profileSettings: "Configurações de Perfil",
    updateProfile: "Atualizar Perfil",
    profileUpdated: "Perfil atualizado com sucesso!",
    uploadPhoto: "Enviar Foto",
    removePhoto: "Remover Foto",
    photoDescription: "Envie uma foto sua para personalizar o perfil.",
    typeMessage: "Digite uma mensagem...",
    send: "Enviar",
    noMessages: "Nenhuma mensagem ainda. Diga olá!",
    country: "País",
    holiday: "Feriado",
    totalDays: "Dias Trabalhados",
    helpTitle: "Como podemos ajudar?",
    helpSubtitle: "Pergunte ao Axis, nosso Assistente Digital",
    contactSupport: "Falar com Suporte Humano",
    botPlaceholder: "Ex: Como exporto para PDF?",
    ticketCreated: "Seu pedido foi enviado para o suporte técnico. Entraremos em contato em breve.",
    botName: "Axis",
    helpWelcome: "Olá! Sou o Axis, o seu assistente. Pode escrever no seu idioma — eu compreendo todos. Em que posso ajudar?",
    joinDiscount: "Quero aderir com DESCONTO!",
    alreadyActive: "Já ativei minha conta! Quero fazer Login",
    salesPageTitle: "Ative sua conta Digital Nexus",
    planMonthly: "Plano Mensal - Acesso Total",
    paymentMethod: "Método de Pagamento",
    mbway: "MBWAY",
    creditCard: "Cartão de Crédito",
    cardNumber: "Número do Cartão",
    expiryDate: "Validade (MM/AA)",
    cvv: "CVV",
    payAndActivate: "Pagar e Ativar Conta",
    processingPayment: "Processando pagamento...",
    paymentSuccess: "Pagamento confirmado! Sua conta foi criada.",
    mbwayNumber: "Número de Celular MBWAY",
    planYearly: "Apenas 1 pagamento por ano",
    unlimitedAccess: "Acesso ILIMITADO",
    memberChat: "Chat entre membros",
    continueToPayment: "Continuar para Pagamento",
    back: "Voltar",
    limitedOfferApplied: "OFERTA LIMITADA aplicada",
    totalToday: "Total Hoje",
    perYear: "/ano",
    exportFeatures: "Exportar PDF/Excel",
    support247: "Suporte 24h/7",
    backupData: "Backup de Dados",
    backupSuccess: "Backup baixado com sucesso!",
    restoreBackup: "Restaurar Backup",
    restoreSuccess: "Dados restaurados com sucesso!",
    invalidBackupFile: "Arquivo de backup inválido.",
    workSite: "Local/Serviço",
    observations: "Observações"
  },
  en: {
    welcome: "Welcome",
    goodMorning: "Good Morning",
    goodAfternoon: "Good Afternoon",
    goodEvening: "Good Evening",
    login: "Login",
    username: "Username",
    password: "Password",
    dashboard: "Dashboard",
    reports: "Reports",
    profile: "Profile",
    chat: "Chat / Network",
    help: "Help",
    settings: "Settings",
    logout: "Logout",
    clockIn: "Clock In",
    clockOut: "Clock Out",
    date: "Date",
    startTime: "Start Time",
    endTime: "End Time",
    lunch: "Lunch (min)",
    notes: "Notes",
    save: "Save",
    cancel: "Cancel",
    absent: "Mark Absent",
    present: "Present",
    totalHours: "Total Hours",
    expectedHours: "Expected Hours",
    balance: "Balance",
    exportPDF: "Export PDF",
    exportExcel: "Export Excel",
    mon: "Mon",
    tue: "Tue",
    wed: "Wed",
    thu: "Thu",
    fri: "Fri",
    sat: "Sat",
    sun: "Sun",
    hoursWorked: "Hours Worked",
    dailyGoal: "Daily Goal (8h)",
    status: "Status",
    editRecord: "Edit Record",
    companyName: "Digital Nexus Solutions",
    adminDashboard: "Subscription Management",
    activeSubscriptions: "Active Subscriptions",
    newSubscription: "New Subscription",
    fullName: "Full Name",
    nif: "Tax ID",
    email: "Email",
    phone: "Phone",
    hourlyRate: "Hourly Rate",
    createAccount: "Create Account",
    noUsers: "No users registered.",
    id: "ID",
    actions: "Actions",
    editUser: "Edit User",
    deleteUser: "Delete",
    confirmDelete: "Are you sure you want to delete this user?",
    generatedId: "Generated ID",
    changePassword: "Change Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    passwordMismatch: "Passwords do not match",
    provisionalPasswordNotice: "You are using a provisional password. Please set a new password.",
    resetPassword: "Reset Password (123)",
    passwordResetSuccess: "Password reset to '123' successfully.",
    socialSecurity: "Social Security",
    irs: "Income Tax (IRS)",
    socialSecurityManual: "Soc. Security (Manual)",
    advance: "Advance",
    advancesReceived: "Advances Received",
    totalAdvances: "Total Advances",
    deductionType: "Deduction Type",
    percentage: "Percentage (%)",
    fixedValue: "Fixed Value",
    value: "Value",
    netEarnings: "Net Earnings",
    grossEarnings: "Gross Earnings",
    profileSettings: "Profile Settings",
    updateProfile: "Update Profile",
    profileUpdated: "Profile updated successfully!",
    uploadPhoto: "Upload Photo",
    removePhoto: "Remove Photo",
    photoDescription: "Upload a photo of yourself to customize your profile.",
    typeMessage: "Type a message...",
    send: "Send",
    noMessages: "No messages yet. Say hello!",
    country: "Country",
    holiday: "Holiday",
    totalDays: "Days Worked",
    helpTitle: "How can we help?",
    helpSubtitle: "Ask Axis, our Digital Assistant",
    contactSupport: "Contact Human Support",
    botPlaceholder: "Ex: How do I export to PDF?",
    ticketCreated: "Your request has been forwarded to technical support. We will contact you shortly.",
    botName: "Axis",
    helpWelcome: "Hello! I am Axis, your assistant. You can write in your language — I understand them all. How can I help?",
    joinDiscount: "Join with DISCOUNT!",
    alreadyActive: "Already Active! Login",
    salesPageTitle: "Activate your Digital Nexus Account",
    planMonthly: "Monthly Plan - Full Access",
    paymentMethod: "Payment Method",
    mbway: "MBWAY",
    creditCard: "Credit Card",
    cardNumber: "Card Number",
    expiryDate: "Expiry (MM/YY)",
    cvv: "CVV",
    payAndActivate: "Pay & Activate Account",
    processingPayment: "Processing payment...",
    paymentSuccess: "Payment confirmed! Your account has been created.",
    mbwayNumber: "MBWAY Phone Number",
    planYearly: "Only 1 payment per year",
    unlimitedAccess: "UNLIMITED Access",
    memberChat: "Member Chat",
    continueToPayment: "Continue to Payment",
    back: "Back",
    limitedOfferApplied: "LIMITED OFFER applied",
    totalToday: "Total Today",
    perYear: "/year",
    exportFeatures: "Export PDF/Excel",
    support247: "24/7 Support",
    backupData: "Backup Data",
    backupSuccess: "Backup downloaded successfully!",
    restoreBackup: "Restore Backup",
    restoreSuccess: "Data restored successfully!",
    invalidBackupFile: "Invalid backup file.",
    workSite: "Location/Work Site",
    observations: "Observations"
  },
  es: {
    welcome: "Bienvenido",
    goodMorning: "Buenos Días",
    goodAfternoon: "Buenas Tardes",
    goodEvening: "Buenas Noches",
    login: "Acceso",
    username: "Usuario",
    password: "Password",
    dashboard: "Tablero",
    reports: "Informes",
    profile: "Perfil",
    chat: "Chat / Red",
    help: "Ayuda",
    settings: "Ajustes",
    logout: "Cerrar sesión",
    clockIn: "Entrada",
    clockOut: "Salida",
    date: "Fecha",
    startTime: "Hora Inicio",
    endTime: "Hora Fin",
    lunch: "Almuerzo (min)",
    notes: "Observaciones",
    save: "Guardar",
    cancel: "Cancelar",
    absent: "Marcar Ausencia",
    present: "Presente",
    totalHours: "Horas Totales",
    expectedHours: "Horas Esperadas",
    balance: "Balance",
    exportPDF: "Exportar PDF",
    exportExcel: "Exportar Excel",
    mon: "Lun",
    tue: "Mar",
    wed: "Mié",
    thu: "Jue",
    fri: "Vie",
    sat: "Sáb",
    sun: "Dom",
    hoursWorked: "Horas Trabajadas",
    dailyGoal: "Meta Diaria (8h)",
    status: "Estado",
    editRecord: "Editar Registro",
    companyName: "Digital Nexus Solutions",
    adminDashboard: "Gestión de Suscripciones",
    activeSubscriptions: "Suscripciones Activas",
    newSubscription: "Nueva Suscripción",
    fullName: "Nombre Completo",
    nif: "NIF",
    email: "Email",
    phone: "Teléfono",
    hourlyRate: "Tarifa por Hora",
    createAccount: "Crear Cuenta",
    noUsers: "Ningún usuario registrado.",
    id: "ID",
    actions: "Acciones",
    editUser: "Editar Usuario",
    deleteUser: "Eliminar",
    confirmDelete: "¿Está seguro de que desea eliminar a este usuario?",
    generatedId: "ID Generado",
    changePassword: "Cambiar Contraseña",
    newPassword: "Nueva Contraseña",
    confirmPassword: "Confirmar Contraseña",
    passwordMismatch: "Las contraseñas no coinciden",
    provisionalPasswordNotice: "Está utilizando una contraseña provisional. Por favor, establezca una nueva.",
    resetPassword: "Restablecer contraseña (123)",
    passwordResetSuccess: "Contraseña restablecida a '123' con éxito.",
    socialSecurity: "Seguridad Social",
    irs: "IRPF (Impuesto)",
    socialSecurityManual: "Seg. Social (Manual)",
    advance: "Anticipo",
    advancesReceived: "Anticipos Recibidos",
    totalAdvances: "Total Anticipos",
    deductionType: "Tipo de Deducción",
    percentage: "Porcentaje (%)",
    fixedValue: "Valor Fijo",
    value: "Valor",
    netEarnings: "Ganancias Netas",
    grossEarnings: "Ganancias Brutas",
    profileSettings: "Configuración del Perfil",
    updateProfile: "Actualizar Perfil",
    profileUpdated: "¡Perfil actualizado con éxito!",
    uploadPhoto: "Subir Foto",
    removePhoto: "Eliminar Foto",
    photoDescription: "Sube una foto tuya para personalizar tu perfil.",
    typeMessage: "Escribe un mensaje...",
    send: "Enviar",
    noMessages: "No hay mensajes todavía. ¡Di hola!",
    country: "País",
    holiday: "Festivo",
    totalDays: "Días Trabajados",
    helpTitle: "¿Cómo podemos ayudar?",
    helpSubtitle: "Pregunta a Axis, nuestro Asistente Digital",
    contactSupport: "Contactar Soporte Humano",
    botPlaceholder: "Ej: ¿Cómo exporto a PDF?",
    ticketCreated: "Su solicitud ha sido enviada a soporte técnico. Nos pondremos en contacto pronto.",
    botName: "Axis",
    helpWelcome: "¡Hola! Soy Axis, tu asistente. Puedes escribir en tu idioma — los entiendo todos. ¿En qué puedo ayudarte?",
    joinDiscount: "¡Únete con DESCUENTO!",
    alreadyActive: "¡Ya activo! Iniciar Sesión",
    salesPageTitle: "Activa tu cuenta Digital Nexus",
    planMonthly: "Plan Mensual - Acceso Total",
    paymentMethod: "Método de Pago",
    mbway: "MBWAY",
    creditCard: "Tarjeta de Crédito",
    cardNumber: "Número de Tarjeta",
    expiryDate: "Caducidad (MM/AA)",
    cvv: "CVV",
    payAndActivate: "Pagar y Activar Cuenta",
    processingPayment: "Procesando pago...",
    paymentSuccess: "¡Pago confirmado! Tu cuenta ha sido creada.",
    mbwayNumber: "Número de Móvil MBWAY",
    planYearly: "Solo 1 pago por año",
    unlimitedAccess: "Acceso ILIMITADO",
    memberChat: "Chat entre miembros",
    continueToPayment: "Continuar al Pago",
    back: "Atrás",
    limitedOfferApplied: "OFERTA LIMITADA aplicada",
    totalToday: "Total Hoy",
    perYear: "/año",
    exportFeatures: "Exportar PDF/Excel",
    support247: "Soporte 24/7",
    backupData: "Copia de Seguridad",
    backupSuccess: "¡Copia de seguridad descargada con éxito!",
    restoreBackup: "Restaurar Copia",
    restoreSuccess: "¡Datos restaurados con éxito!",
    invalidBackupFile: "Archivo de copia de seguridad no válido.",
    workSite: "Local/Obra",
    observations: "Observaciones"
  },
  fr: {
    welcome: "Bienvenue",
    goodMorning: "Bonjour",
    goodAfternoon: "Bonne Après-midi",
    goodEvening: "Bonne Soirée",
    login: "Connexion",
    username: "Nom d'utilisateur",
    password: "Mot de passe",
    dashboard: "Tableau de bord",
    reports: "Rapports",
    profile: "Profil",
    chat: "Chat / Réseau",
    help: "Aide",
    settings: "Paramètres",
    logout: "Déconnexion",
    clockIn: "Pointer l'entrée",
    clockOut: "Pointer la sortie",
    date: "Date",
    startTime: "Heure Début",
    endTime: "Heure Fin",
    lunch: "Déjeuner (min)",
    notes: "Remarques",
    save: "Enregistrer",
    cancel: "Annuler",
    absent: "Marquer Absent",
    present: "Présent",
    totalHours: "Heures Totales",
    expectedHours: "Heures Prévues",
    balance: "Solde",
    exportPDF: "Exporter PDF",
    exportExcel: "Exporter Excel",
    mon: "Lun",
    tue: "Mar",
    wed: "Mer",
    thu: "Jeu",
    fri: "Ven",
    sat: "Sam",
    sun: "Dim",
    hoursWorked: "Heures Travaillées",
    dailyGoal: "Objectif (8h)",
    status: "Statut",
    editRecord: "Modifier",
    companyName: "Digital Nexus Solutions",
    adminDashboard: "Gestion des Abonnements",
    activeSubscriptions: "Abonnements Actifs",
    newSubscription: "Nouvel Abonnement",
    fullName: "Nom Complet",
    nif: "NIF",
    email: "Email",
    phone: "Téléphone",
    hourlyRate: "Taux Horaire",
    createAccount: "Créer Compte",
    noUsers: "Aucun utilisateur enregistré.",
    id: "ID",
    actions: "Actions",
    editUser: "Modifier Utilisateur",
    deleteUser: "Supprimer",
    confirmDelete: "Êtes-vous sûr de vouloir supprimer cet utilisateur ?",
    generatedId: "ID Généré",
    changePassword: "Changer le mot de passe",
    newPassword: "Nouveau mot de passe",
    confirmPassword: "Confirmer le mot de passe",
    passwordMismatch: "Les mots de passe ne correspondent pas",
    provisionalPasswordNotice: "Vous utilisez un mot de passe provisoire. Veuillez en définir un nouveau.",
    resetPassword: "Réinitialiser mot de passe (123)",
    passwordResetSuccess: "Mot de passe réinitialisé à '123' avec succès.",
    socialSecurity: "Sécurité Sociale",
    irs: "Impôt sur le revenu",
    socialSecurityManual: "Séc. Sociale (Manuel)",
    advance: "Avance",
    advancesReceived: "Avances Reçues",
    totalAdvances: "Total Avances",
    deductionType: "Type de Déduction",
    percentage: "Pourcentage (%)",
    fixedValue: "Valeur Fixe",
    value: "Valeur",
    netEarnings: "Gains Nets",
    grossEarnings: "Gains Bruts",
    profileSettings: "Paramètres du Profil",
    updateProfile: "Mettre à jour le profil",
    profileUpdated: "Profil mis à jour avec succès !",
    uploadPhoto: "Télécharger Photo",
    removePhoto: "Supprimer Photo",
    photoDescription: "Téléchargez une photo de vous pour personnaliser votre profil.",
    typeMessage: "Écrivez un message...",
    send: "Envoyer",
    noMessages: "Pas encore de messages. Dites bonjour !",
    country: "Pays",
    holiday: "Férié",
    totalDays: "Jours Travaillés",
    helpTitle: "Comment pouvons-nous aider ?",
    helpSubtitle: "Demandez à Axis, notre Assistant Digital",
    contactSupport: "Contacter le Support Humain",
    botPlaceholder: "Ex: Comment exporter en PDF ?",
    ticketCreated: "Votre demande a été transmise au support technique. Nous vous contacterons bientôt.",
    botName: "Axis",
    helpWelcome: "Bonjour ! Je suis Axis, votre assistant. Vous pouvez écrire dans votre langue — je les comprends toutes. Comment puis-je vous aider ?",
    joinDiscount: "Rejoignez avec REMISE !",
    alreadyActive: "Déjà Actif ! Connexion",
    salesPageTitle: "Activez votre compte Digital Nexus",
    planMonthly: "Plan Mensuel - Accès Complet",
    paymentMethod: "Mode de Paiement",
    mbway: "MBWAY",
    creditCard: "Carte de Crédit",
    cardNumber: "Numéro de Carte",
    expiryDate: "Expiration (MM/AA)",
    cvv: "CVV",
    payAndActivate: "Payer et Activer le Compte",
    processingPayment: "Traitement du paiement...",
    paymentSuccess: "Paiement confirmé ! Votre compte a été créé.",
    mbwayNumber: "Numéro de Mobile MBWAY",
    planYearly: "Un seul paiement par an",
    unlimitedAccess: "Accès ILLIMITÉ",
    memberChat: "Chat entre membres",
    continueToPayment: "Continuer vers le Paiement",
    back: "Retour",
    limitedOfferApplied: "OFFRE LIMITÉE appliquée",
    totalToday: "Total Aujourd'hui",
    perYear: "/an",
    exportFeatures: "Exporter PDF/Excel",
    support247: "Support 24/7",
    backupData: "Sauvegarde des Données",
    backupSuccess: "Sauvegarde téléchargée avec succès !",
    restoreBackup: "Restaurer la Sauvegarde",
    restoreSuccess: "Données restaurées avec succès !",
    invalidBackupFile: "Fichier de sauvegarde invalide.",
    workSite: "Lieu/Chantier",
    observations: "Observations"
  },
  it: {
    welcome: "Benvenuto",
    goodMorning: "Buongiorno",
    goodAfternoon: "Buon Pomeriggio",
    goodEvening: "Buonasera",
    login: "Accedi",
    username: "Nome Utente",
    password: "Password",
    dashboard: "Dashboard",
    reports: "Rapporti",
    profile: "Profilo",
    chat: "Chat / Rete",
    help: "Aiuto",
    settings: "Impostazioni",
    logout: "Esci",
    clockIn: "Entrata",
    clockOut: "Uscita",
    date: "Data",
    startTime: "Ora Inizio",
    endTime: "Ora Fine",
    lunch: "Pranzo (min)",
    notes: "Note",
    save: "Salva",
    cancel: "Annulla",
    absent: "Segna Assenza",
    present: "Presente",
    totalHours: "Ore Totali",
    expectedHours: "Ore Previste",
    balance: "Saldo",
    exportPDF: "Esporta PDF",
    exportExcel: "Esporta Excel",
    mon: "Lun",
    tue: "Mar",
    wed: "Mer",
    thu: "Gio",
    fri: "Ven",
    sat: "Sab",
    sun: "Dom",
    hoursWorked: "Ore Lavorate",
    dailyGoal: "Obiettivo (8h)",
    status: "Stato",
    editRecord: "Modifica",
    companyName: "Digital Nexus Solutions",
    adminDashboard: "Gestione Abbonamenti",
    activeSubscriptions: "Abbonamenti Attivi",
    newSubscription: "Nuovo Abbonamento",
    fullName: "Nome Completo",
    nif: "Codice Fiscale",
    email: "Email",
    phone: "Telefono",
    hourlyRate: "Tariffa Oraria",
    createAccount: "Crea Account",
    noUsers: "Nessun utente registrato.",
    id: "ID",
    actions: "Azioni",
    editUser: "Modifica Utente",
    deleteUser: "Elimina",
    confirmDelete: "Sei sicuro di voler eliminare questo utente?",
    generatedId: "ID Generado",
    changePassword: "Cambia Password",
    newPassword: "Nuova Password",
    confirmPassword: "Conferma Password",
    passwordMismatch: "Le password non corrispondono",
    provisionalPasswordNotice: "Stai usando una password provisoria. Impostane una nuova.",
    resetPassword: "Reimposta Password (123)",
    passwordResetSuccess: "Password reimpostata a '123' con successo.",
    socialSecurity: "Previdenza Sociale",
    irs: "Imposta sul Reddito (IRPEF)",
    socialSecurityManual: "Prev. Sociale (Manuale)",
    advance: "Anticipo",
    advancesReceived: "Anticipi Ricevuti",
    totalAdvances: "Totale Anticipi",
    deductionType: "Tipo di Detrazione",
    percentage: "Percentuale (%)",
    fixedValue: "Valore Fisso",
    value: "Valore",
    netEarnings: "Guadagno Netto",
    grossEarnings: "Guadagno Lordo",
    profileSettings: "Impostazioni Profilo",
    updateProfile: "Aggiorna Profilo",
    profileUpdated: "Profilo aggiornato con successo!",
    uploadPhoto: "Carica Foto",
    removePhoto: "Rimuovi Foto",
    photoDescription: "Carica una tua foto per personalizzare il tuo profilo.",
    typeMessage: "Scrivi un messaggio...",
    send: "Invia",
    noMessages: "Nessun messaggio ancora. Dì ciao!",
    country: "Paese",
    holiday: "Vacanza",
    totalDays: "Giorni Lavorati",
    helpTitle: "Come possiamo aiutare?",
    helpSubtitle: "Chiedi ad Axis, il nostro Assistente Digitale",
    contactSupport: "Contatta Supporto Umano",
    botPlaceholder: "Es: Come esporto in PDF?",
    ticketCreated: "La tua richiesta è stata inoltrata al supporto tecnico. Ti contatteremo a breve.",
    botName: "Axis",
    helpWelcome: "Ciao! Sono Axis, il tuo assistente. Puoi scrivere nella tua lingua — le capisco tutte. Come posso aiutarti?",
    joinDiscount: "Unisciti con SCONTO!",
    alreadyActive: "Già attivo! Accedi",
    salesPageTitle: "Attiva il tuo account Digital Nexus",
    planMonthly: "Piano Mensile - Accesso Completo",
    paymentMethod: "Metodo di Pagamento",
    mbway: "MBWAY",
    creditCard: "Carta di Credito",
    cardNumber: "Numero Carta",
    expiryDate: "Scadenza (MM/AA)",
    cvv: "CVV",
    payAndActivate: "Paga e Attiva Account",
    processingPayment: "Elaborazione pagamento...",
    paymentSuccess: "Pagamento confermato! Il tuo account è stato creato.",
    mbwayNumber: "Numero Cellulare MBWAY",
    planYearly: "Solo 1 pagamento all'anno",
    unlimitedAccess: "Accesso ILLIMITATO",
    memberChat: "Chat tra i membri",
    continueToPayment: "Continua al Pagamento",
    back: "Indietro",
    limitedOfferApplied: "OFFERTA LIMITATA applicata",
    totalToday: "Totale Oggi",
    perYear: "/anno",
    exportFeatures: "Esporta PDF/Excel",
    support247: "Supporto 24/7",
    backupData: "Backup dei Dati",
    backupSuccess: "Backup scaricato con successo!",
    restoreBackup: "Ripristina Backup",
    restoreSuccess: "Dati ripristinati con successo!",
    invalidBackupFile: "File di backup non valido.",
    workSite: "Luogo/Cantiere",
    observations: "Osservazioni"
  },
  de: {
    welcome: "Willkommen",
    goodMorning: "Guten Morgen",
    goodAfternoon: "Guten Tag",
    goodEvening: "Guten Abend",
    login: "Anmelden",
    username: "Benutzername",
    password: "Passwort",
    dashboard: "Dashboard",
    reports: "Berichte",
    profile: "Profil",
    chat: "Chat / Netzwerk",
    help: "Hilfe",
    settings: "Einstellungen",
    logout: "Abmelden",
    clockIn: "Einstempeln",
    clockOut: "Ausstempeln",
    date: "Datum",
    startTime: "Startzeit",
    endTime: "Endzeit",
    lunch: "Mittag (min)",
    notes: "Notizen",
    save: "Speichern",
    cancel: "Abbrechen",
    absent: "Abwesend markieren",
    present: "Anwesend",
    totalHours: "Gesamtstunden",
    expectedHours: "Erwartete Stunden",
    balance: "Saldo",
    exportPDF: "PDF Exportieren",
    exportExcel: "Excel Exportieren",
    mon: "Mo",
    tue: "Di",
    wed: "Mi",
    thu: "Do",
    fri: "Fr",
    sat: "Sa",
    sun: "So",
    hoursWorked: "Arbeitsstunden",
    dailyGoal: "Tagesziel (8h)",
    status: "Status",
    editRecord: "Eintrag bearbeiten",
    companyName: "Digital Nexus Solutions",
    adminDashboard: "Abonnementverwaltung",
    activeSubscriptions: "Aktive Abonnements",
    newSubscription: "Neues Abonnement",
    fullName: "Vollständiger Name",
    nif: "Steuernummer",
    email: "E-Mail",
    phone: "Telefon",
    hourlyRate: "Stundensatz",
    createAccount: "Konto erstellen",
    noUsers: "Keine Benutzer registriert.",
    id: "ID",
    actions: "Aktionen",
    editUser: "Benutzer bearbeiten",
    deleteUser: "Löschen",
    confirmDelete: "Sind Sie sicher, dass Sie diesen Benutzer löschen möchten?",
    generatedId: "Generierte ID",
    changePassword: "Passwort ändern",
    newPassword: "Neues Passwort",
    confirmPassword: "Passwort bestätigen",
    passwordMismatch: "Passwörter stimmen nicht überein",
    provisionalPasswordNotice: "Sie verwenden ein vorläufiges Passwort. Bitte legen Sie ein neues fest.",
    resetPassword: "Passwort zurücksetzen (123)",
    passwordResetSuccess: "Passwort erfolgreich auf '123' zurückgesetzt.",
    socialSecurity: "Sozialversicherung",
    irs: "Einkommensteuer",
    socialSecurityManual: "Sozialvers. (Manuell)",
    advance: "Vorschuss",
    advancesReceived: "Erhaltene Vorschüsse",
    totalAdvances: "Gesamtvorschüsse",
    deductionType: "Abzugsart",
    percentage: "Prozentsatz (%)",
    fixedValue: "Fester Wert",
    value: "Wert",
    netEarnings: "Nettoeinkommen",
    grossEarnings: "Bruttoeinkommen",
    profileSettings: "Profileinstellungen",
    updateProfile: "Profil aktualisieren",
    profileUpdated: "Profil erfolgreich aktualisiert!",
    uploadPhoto: "Foto Hochladen",
    removePhoto: "Foto Entfernen",
    photoDescription: "Laden Sie ein Foto von sich hoch, um Ihr Profil anzupassen.",
    typeMessage: "Nachricht eingeben...",
    send: "Senden",
    noMessages: "Noch keine Nachrichten. Sag Hallo!",
    country: "Land",
    holiday: "Feiertag",
    totalDays: "Arbeitstage",
    helpTitle: "Wie können wir helfen?",
    helpSubtitle: "Fragen Sie Axis, unseren Digitalen Assistenten",
    contactSupport: "Menschlichen Support kontaktieren",
    botPlaceholder: "Bsp: Wie exportiere ich PDF?",
    ticketCreated: "Ihre Anfrage wurde an den technischen Support weitergeleitet. Wir melden uns in Kürze.",
    botName: "Axis",
    helpWelcome: "Hallo! Ich bin Axis, Ihr Assistent. Sie können in Ihrer Sprache schreiben – ich verstehe alle. Wie kann ich Ihnen helfen?",
    joinDiscount: "Mit RABATT beitreten!",
    alreadyActive: "Bereits aktiv! Anmelden",
    salesPageTitle: "Aktivieren Sie Ihr Digital Nexus Konto",
    planMonthly: "Monatsplan - Voller Zugriff",
    paymentMethod: "Zahlungsmethode",
    mbway: "MBWAY",
    creditCard: "Kreditkarte",
    cardNumber: "Kartennummer",
    expiryDate: "Ablauf (MM/JJ)",
    cvv: "CVV",
    payAndActivate: "Zahlen & Konto aktivieren",
    processingPayment: "Zahlung wird verarbeitet...",
    paymentSuccess: "Zahlung bestätigt! Ihr Konto wurde erstellt.",
    mbwayNumber: "MBWAY Handynummer",
    planYearly: "Nur 1 Zahlung pro Jahr",
    unlimitedAccess: "UNBEGRENZTER Zugang",
    memberChat: "Chat zwischen Mitgliedern",
    continueToPayment: "Weiter zur Zahlung",
    back: "Zurück",
    limitedOfferApplied: "BEGRENZTES ANGEBOT angewendet",
    totalToday: "Gesamt Heute",
    perYear: "/jahr",
    exportFeatures: "PDF/Excel exportieren",
    support247: "24/7 Support",
    backupData: "Datensicherung",
    backupSuccess: "Backup erfolgreich heruntergeladen!",
    restoreBackup: "Backup wiederherstellen",
    restoreSuccess: "Daten erfolgreich wiederhergestellt!",
    invalidBackupFile: "Ungültige Sicherungsdatei.",
    workSite: "Standort/Baustelle",
    observations: "Beobachtungen"
  },
  nl: {
    welcome: "Welkom",
    goodMorning: "Goedemorgen",
    goodAfternoon: "Goedemiddag",
    goodEvening: "Goedenavond",
    login: "Inloggen",
    username: "Gebruikersnaam",
    password: "Wachtwoord",
    dashboard: "Dashboard",
    reports: "Rapporten",
    profile: "Profiel",
    chat: "Chat / Netwerk",
    help: "Hulp",
    settings: "Instellingen",
    logout: "Uitloggen",
    clockIn: "Inklokken",
    clockOut: "Uitklokken",
    date: "Datum",
    startTime: "Starttijd",
    endTime: "Eindtijd",
    lunch: "Lunch (min)",
    notes: "Notities",
    save: "Opslaan",
    cancel: "Annuleren",
    absent: "Afwezig melden",
    present: "Aanwezig",
    totalHours: "Totaal Uren",
    expectedHours: "Verwachte Uren",
    balance: "Saldo",
    exportPDF: "Exporteer PDF",
    exportExcel: "Exporteer Excel",
    mon: "Ma",
    tue: "Di",
    wed: "Wo",
    thu: "Do",
    fri: "Vr",
    sat: "Za",
    sun: "Zo",
    hoursWorked: "Gewerkte Uren",
    dailyGoal: "Dagdoel (8u)",
    status: "Status",
    editRecord: "Record Bewerken",
    companyName: "Digital Nexus Solutions",
    adminDashboard: "Abonnementbeheer",
    activeSubscriptions: "Actieve Abonnementen",
    newSubscription: "Nieuw Abonnement",
    fullName: "Volledige Naam",
    nif: "Btw-nummer",
    email: "E-mail",
    phone: "Telefoon",
    hourlyRate: "Uurtarief",
    createAccount: "Account Aanmaken",
    noUsers: "Geen gebruikers geregistreerd.",
    id: "ID",
    actions: "Acties",
    editUser: "Gebruiker Bewerken",
    deleteUser: "Verwijderen",
    confirmDelete: "Weet u zeker dat u deze gebruiker wilt verwijderen?",
    generatedId: "Gegenereerde ID",
    changePassword: "Wachtwoord Wijzigen",
    newPassword: "Nieuw Wachtwoord",
    confirmPassword: "Bevestig Wachtwoord",
    passwordMismatch: "Wachtwoorden komen niet overeen",
    provisionalPasswordNotice: "U gebruikt een tijdelijk wachtwoord. Stel een nieuw wachtwoord in.",
    resetPassword: "Wachtwoord Resetten (123)",
    passwordResetSuccess: "Wachtwoord succesvol gereset naar '123'.",
    socialSecurity: "Sociale Zekerheid",
    irs: "Inkomstenbelasting",
    socialSecurityManual: "Soc. Zekerheid (Handmatig)",
    advance: "Voorschot",
    advancesReceived: "Ontvangen Voorschotten",
    totalAdvances: "Totaal Voorschotten",
    deductionType: "Type Inhouding",
    percentage: "Percentage (%)",
    fixedValue: "Vaste Waarde",
    value: "Waarde",
    netEarnings: "Netto Inkomsten",
    grossEarnings: "Bruto Inkomsten",
    profileSettings: "Profielinstellingen",
    updateProfile: "Profiel Bijwerken",
    profileUpdated: "Profiel succesvol bijgewerkt!",
    uploadPhoto: "Foto Uploaden",
    removePhoto: "Foto Verwijderen",
    photoDescription: "Upload een foto van jezelf om je profiel aan te passen.",
    typeMessage: "Typ een bericht...",
    send: "Verstuur",
    noMessages: "Nog geen berichten. Zeg hallo!",
    country: "Land",
    holiday: "Vakantie",
    totalDays: "Gewerkte Dagen",
    helpTitle: "Hoe kunnen we helpen?",
    helpSubtitle: "Vraag Axis, onze Digital Nexus Assistent",
    contactSupport: "Neem contact op met menselijke ondersteuning",
    botPlaceholder: "Bijv: Hoe exporteer ik PDF?",
    ticketCreated: "Uw verzoek is doorgestuurd naar de technische ondersteuning. We nemen binnenkort contact met u op.",
    botName: "Axis",
    helpWelcome: "Hallo! Ik ben Axis, uw assistent. U kunt in uw eigen taal schrijven — ik begrijp ze allemaal. Hoe kan ik u helpen?",
    joinDiscount: "Word lid met KORTING!",
    alreadyActive: "Al actief! Inloggen",
    salesPageTitle: "Activeer uw Digital Nexus-account",
    planMonthly: "Maandabonnement - Volledige Toegang",
    paymentMethod: "Betaalmethode",
    mbway: "MBWAY",
    creditCard: "Creditcard",
    cardNumber: "Kaartnummer",
    expiryDate: "Vervaldatum (MM/JJ)",
    cvv: "CVV",
    payAndActivate: "Betalen & Account Activeren",
    processingPayment: "Betaling verwerken...",
    paymentSuccess: "Betaling bevestigd! Uw account is aangemaakt.",
    mbwayNumber: "MBWAY Mobiel Nummer",
    planYearly: "Slechts 1 betaling per jaar",
    unlimitedAccess: "ONBEPERKTE Toegang",
    memberChat: "Chat tussen leden",
    continueToPayment: "Doorgaan naar betaling",
    back: "Terug",
    limitedOfferApplied: "BEPERKTE AANBIEDING toegepast",
    totalToday: "Totaal vandaag",
    perYear: "/jaar",
    exportFeatures: "PDF/Excel exporteren",
    support247: "24/7 Ondersteuning",
    backupData: "Back-upgegevens",
    backupSuccess: "Back-up succesvol gedownload!",
    restoreBackup: "Back-up herstellen",
    restoreSuccess: "Gegevens succesvol hersteld!",
    invalidBackupFile: "Ongeldig back-upbestand.",
    workSite: "Locatie/Werkplek",
    observations: "Opmerkingen"
  },
  ga: {
    welcome: "Fáilte",
    goodMorning: "Maidin mhaith",
    goodAfternoon: "Tráthnóna maith",
    goodEvening: "Oíche mhaith",
    login: "Logáil isteach",
    username: "Ainm Úsáideora",
    password: "Focal Faire",
    dashboard: "Deais",
    reports: "Tuairiscí",
    profile: "Próifíl",
    chat: "Comhrá / Líonra",
    help: "Cabhair",
    settings: "Socruithe",
    logout: "Logáil Amach",
    clockIn: "Cláraigh Isteach",
    clockOut: "Cláraigh Amach",
    date: "Dáta",
    startTime: "Am Tosaithe",
    endTime: "Am Críochnaithe",
    lunch: "Lón (nóim)",
    notes: "Nótaí",
    save: "Sábháil",
    cancel: "Cealaigh",
    absent: "Marcáil As Láthair",
    present: "I Láthair",
    totalHours: "Uaireanta Iomlána",
    expectedHours: "Uaireanta atá ag Teastáil",
    balance: "Iarmhéid",
    exportPDF: "Easpórtáil PDF",
    exportExcel: "Easpórtáil Excel",
    mon: "Luan",
    tue: "Máirt",
    wed: "Céad",
    thu: "Déar",
    fri: "Aoine",
    sat: "Sath",
    sun: "Domh",
    hoursWorked: "Uaireanta Oibre",
    dailyGoal: "Sprioc Laethúil (8u)",
    status: "Stádas",
    editRecord: "Cuir Eagar ar Thaifead",
    companyName: "Digital Nexus Solutions",
    adminDashboard: "Bainistíocht Síntiúis",
    activeSubscriptions: "Síntiúis Ghníomhacha",
    newSubscription: "Síntiús Nua",
    fullName: "Ainm Iomlán",
    nif: "Uimhir Cánach",
    email: "Ríomhphost",
    phone: "Guthán",
    hourlyRate: "Ráta san Uair",
    createAccount: "Cruthaigh Cuntas",
    noUsers: "Níl aon úsáideoirí cláraithe.",
    id: "ID",
    actions: "Gníomhartha",
    editUser: "Cuir Eagar ar Úsáideoir",
    deleteUser: "Scrios",
    confirmDelete: "An bhfuil tú cinnte gur mian leat an t-úsáideoir seo a scriosadh?",
    generatedId: "ID Ginie",
    changePassword: "Athraigh Focal Faire",
    newPassword: "Focal Faire Nua",
    confirmPassword: "Deimhnigh Focal Faire",
    passwordMismatch: "Ní mheaitseálann na focail faire",
    provisionalPasswordNotice: "Tá focal faire sealadach á úsáid agat. Socraigh ceann nua le do thoil.",
    resetPassword: "Athshocraigh Focal Faire (123)",
    passwordResetSuccess: "Athshocraíodh an focal faire go '123' go rathúil.",
    socialSecurity: "Leas Sóisialta",
    irs: "Cáin Ioncaim",
    socialSecurityManual: "Leas Sóis. (Lámhleabhar)",
    advance: "Réamhíocaíocht",
    advancesReceived: "Réamhíocaíochtaí Faighte",
    totalAdvances: "Iomlán Réamhíocaíochtaí",
    deductionType: "Cineál Asbhainte",
    percentage: "Céatadán (%)",
    fixedValue: "Luach Seasta",
    value: "Luach",
    netEarnings: "Tuilleamh Glan",
    grossEarnings: "Tuilleamh Comhlán",
    profileSettings: "Socruithe Próifíle",
    updateProfile: "Nuashonraigh Próifíl",
    profileUpdated: "Nuashonraíodh an phróifíl go rathúil!",
    uploadPhoto: "Uaslódáil Grianghraf",
    removePhoto: "Bain Grianghraf",
    photoDescription: "Uaslódáil grianghraf díot féin chun do phróifíl a shaincheapadh.",
    typeMessage: "Clóscríobh teachtaireacht...",
    send: "Seol",
    noMessages: "Níl teachtaireachtaí ann go fóill. Abair halló!",
    country: "Tír",
    holiday: "Saoire",
    totalDays: "Laethanta Oibre",
    helpTitle: "Conas is féidir linn cabhrú?",
    helpSubtitle: "Cuir ceist ar Axis, ár gCúntóir Digiteach",
    contactSupport: "Déan Teagmháil le Tacaíocht Dhaonna",
    botPlaceholder: "m.sh.: Conas a easpórtálaim PDF?",
    ticketCreated: "Tá d'iarratas curtha ar aghaidh chuig tacaíocht theicniúil. Déanfaimid teagmháil leat go luath.",
    botName: "Axis",
    helpWelcome: "Dia duit! Is mise Axis, do chúntóir. Is féidir leat scríobh i do theanga féin — tuigim iad go léir. Conas is féidir liom cabhrú leat?",
    joinDiscount: "Glac páirt le LASCARD!",
    alreadyActive: "Gníomhach Cheana! Logáil isteach",
    salesPageTitle: "Gníomhachtaigh do Chuntas Digital Nexus",
    planMonthly: "Plean Míosúil - Rochtain Iomlán",
    paymentMethod: "Modh Íocaíochta",
    mbway: "MBWAY",
    creditCard: "Cárta Creidmheasa",
    cardNumber: "Uimhir Chárta",
    expiryDate: "Dáta Éaga (MM/BB)",
    cvv: "CVV",
    payAndActivate: "Íoc & Gníomhachtaigh Cuntas",
    processingPayment: "Ag próiseáil íocaíochta...",
    paymentSuccess: "Íocaíocht deimhnithe! Cruthaíodh do chuntas.",
    mbwayNumber: "Uimhir Fón Póca MBWAY",
    planYearly: "Íocaíocht amháin in aghaidh na bliana",
    unlimitedAccess: "Rochtain neamhtheoranta",
    memberChat: "Comhrá idir bhaill",
    continueToPayment: "Lean ar aghaidh go dtí an Íocaíocht",
    back: "Ar ais",
    limitedOfferApplied: "TAIRISCINT THEORANTA curtha i bhfeidhm",
    totalToday: "Iomlán Inniu",
    perYear: "/bliain",
    exportFeatures: "Easpórtáil PDF/Excel",
    support247: "Tacaíocht 24/7",
    backupData: "Cúltaca Sonraí",
    backupSuccess: "D'íoslódáil an cúltaca go rathúil!",
    restoreBackup: "Athchóirigh Cúltaca",
    restoreSuccess: "Athchóiríodh sonraí go rathúil!",
    invalidBackupFile: "Comhad cúltaca neamhbhailí.",
    workSite: "Láithreán Oibre",
    observations: "Tuairimí"
  },
  hi: {
    welcome: "स्वागत हे",
    goodMorning: "सुप्रभात",
    goodAfternoon: "शुभ दोपहर",
    goodEvening: "शुभ संध्या",
    login: "लॉग इन करें",
    username: "उपयोगकर्ता नाम",
    password: "पासवर्ड",
    dashboard: "डैशबोर्ड",
    reports: "रिपोर्ट",
    profile: "प्रोफाइल",
    chat: "चैट / नेटवर्क",
    help: "मदद",
    settings: "सेटिंग्स",
    logout: "लॉग आउट",
    clockIn: "क्लॉक इन",
    clockOut: "क्लॉक आउट",
    date: "तारीख",
    startTime: "शुरू होने का समय",
    endTime: "समाप्ति समय",
    lunch: "दोपहर का भोजन (मिनट)",
    notes: "टिप्पणियाँ",
    save: "सहेजें",
    cancel: "रद्द करें",
    absent: "अनुपस्थित चिह्नित करें",
    present: "उपस्थित",
    totalHours: "कुल घंटे",
    expectedHours: "अपेक्षित घंटे",
    balance: "शेष",
    exportPDF: "PDF निर्यात करें",
    exportExcel: "Excel निर्यात करें",
    mon: "सोम",
    tue: "मंगल",
    wed: "बुध",
    thu: "गुरु",
    fri: "शुक्र",
    sat: "शनि",
    sun: "रवि",
    hoursWorked: "काम के घंटे",
    dailyGoal: "दैनिक लक्ष्य (8 घंटे)",
    status: "स्थिति",
    editRecord: "रिकॉर्ड संपादित करें",
    companyName: "Digital Nexus Solutions",
    adminDashboard: "सदस्यता प्रबंधन",
    activeSubscriptions: "सक्रिय सदस्यताएँ",
    newSubscription: "नई सदस्यता",
    fullName: "पूरा नाम",
    nif: "टैक्स आईडी",
    email: "ईमेल",
    phone: "फ़ोन",
    hourlyRate: "प्रति घंटा दर",
    createAccount: "खाता बनाएं",
    noUsers: "कोई उपयोगकर्ता पंजीकृत नहीं है।",
    id: "आईडी",
    actions: "कार्रवाई",
    editUser: "उपयोगकर्ता संपादित करें",
    deleteUser: "हटाएं",
    confirmDelete: "क्या आप वाकई इस उपयोगकर्ता को हटाना चाहते हैं?",
    generatedId: "जेनरेट की गई आईडी",
    changePassword: "पासवर्ड बदलें",
    newPassword: "नया पासवर्ड",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    passwordMismatch: "पासवर्ड मेल नहीं खाते",
    provisionalPasswordNotice: "आप एक अस्थायी पासवर्ड का उपयोग कर रहे हैं। कृपया एक नया सेट करें।",
    resetPassword: "पासवर्ड रीसेट करें (123)",
    passwordResetSuccess: "पासवर्ड सफलतापूर्वक '123' पर रीसेट कर दिया गया।",
    socialSecurity: "सामाजिक सुरक्षा",
    irs: "आयकर",
    socialSecurityManual: "सा. सुरक्षा (मैनुअल)",
    advance: "अग्रिम",
    advancesReceived: "प्राप्त अग्रिम",
    totalAdvances: "कुल अग्रिम",
    deductionType: "कटौती का प्रकार",
    percentage: "प्रतिशत (%)",
    fixedValue: "निश्चित मूल्य",
    value: "मूल्य",
    netEarnings: "शुद्ध कमाई",
    grossEarnings: "सकल कमाई",
    profileSettings: "प्रोफाइल सेटिंग्स",
    updateProfile: "प्रोफाइल अपडेट करें",
    profileUpdated: "प्रोफाइल सफलतापूर्वक अपडेट की गई!",
    uploadPhoto: "फोटो अपलोड करें",
    removePhoto: "फोटो हटाएं",
    photoDescription: "अपनी प्रोफ़ाइल को अनुकूलित करने के लिए अपनी एक तस्वीर अपलोड करें।",
    typeMessage: "संदेश लिखें...",
    send: "भेजना",
    noMessages: "अभी तक कोई संदेश नहीं। नमस्ते कहो!",
    country: "देश",
    holiday: "छुट्टी",
    totalDays: "काम के दिन",
    helpTitle: "हम आपकी कैसे मदद कर सकते हैं?",
    helpSubtitle: "हमारे डिजिटल सहायक Axis से पूछें",
    contactSupport: "मानव सहायता से संपर्क करें",
    botPlaceholder: "उदा: मैं पीडीएफ कैसे निर्यात करूं?",
    ticketCreated: "आपका अनुरोध तकनीकी सहायता को भेज दिया गया है। हम जल्द ही आपसे संपर्क करेंगे।",
    botName: "Axis",
    helpWelcome: "नमस्ते! मैं एक्सिस हूँ, आपका सहायक। आप अपनी भाषा में लिख सकते हैं — मैं उन सभी को समझता हूँ। मैं आपकी कैसे मदद कर सकता हूँ?",
    joinDiscount: "छूट के साथ जुड़ें!",
    alreadyActive: "पहले से सक्रिय! लॉगिन करें",
    salesPageTitle: "अपने डिजिटल नेक्सस खाते को सक्रिय करें",
    planMonthly: "मासिक योजना - पूर्ण पहुँच",
    paymentMethod: "भुगतान विधि",
    mbway: "MBWAY",
    creditCard: "क्रेडिट कार्ड",
    cardNumber: "कार्ड नंबर",
    expiryDate: "समाप्ति (MM/YY)",
    cvv: "CVV",
    payAndActivate: "भुगतान करें और खाता सक्रिय करें",
    processingPayment: "भुगतान संसाधित हो रहा है...",
    paymentSuccess: "भुगतान की पुष्टि हुई! आपका खाता बना दिया गया है।",
    mbwayNumber: "MBWAY मोबाइल नंबर",
    planYearly: "प्रति वर्ष केवल 1 भुगतान",
    unlimitedAccess: "असीमित पहुंच",
    memberChat: "सदस्य चैट",
    continueToPayment: "भुगतान के लिए जारी रखें",
    back: "वापस",
    limitedOfferApplied: "सीमित प्रस्ताव लागू",
    totalToday: "आज कुल",
    perYear: "/वर्ष",
    exportFeatures: "पीडीएफ/एक्सेल निर्यात करें",
    support247: "24/7 सहायता",
    backupData: "बैकअप डेटा",
    backupSuccess: "बैकअप सफलतापूर्वक डाउनलोड किया गया!",
    restoreBackup: "बैकअप बहाल",
    restoreSuccess: "डेटा सफलतापूर्वक बहाल किया गया!",
    invalidBackupFile: "अमान्य बैकअप फ़ाइल।",
    workSite: "स्थान/कार्य स्थल",
    observations: "टिप्पणियाँ"
  },
  ur: {
    welcome: "خوش آمدید",
    goodMorning: "صبح بخیر",
    goodAfternoon: "سہ پہر بخیر",
    goodEvening: "شام بخیر",
    login: "لاگ ان کریں",
    username: "صارف کا نام",
    password: "پاس ورڈ",
    dashboard: "ڈیش بورڈ",
    reports: "رپورٹس",
    profile: "پروفائل",
    chat: "چیٹ / نیٹ ورک",
    help: "مدد",
    settings: "ترتیبات",
    logout: "لاگ آؤٹ",
    clockIn: "وقت آمد",
    clockOut: "وقت رخصت",
    date: "تاریخ",
    startTime: "شروع کا وقت",
    endTime: "ختم ہونے کا وقت",
    lunch: "دوپہر کا کھانا (منٹ)",
    notes: "نوٹس",
    save: "محفوظ کریں",
    cancel: "منسوخ کریں",
    absent: "غیر حاضر نشان زد کریں",
    present: "موجود",
    totalHours: "کل گھنٹے",
    expectedHours: "متوقع گھنٹے",
    balance: "بیلنس",
    exportPDF: "PDF برآمد کریں",
    exportExcel: "Excel برآمد کریں",
    mon: "پیر",
    tue: "منگل",
    wed: "بدھ",
    thu: "جمعرات",
    fri: "جمعہ",
    sat: "ہفتہ",
    sun: "اتوار",
    hoursWorked: "کام کے گھنٹے",
    dailyGoal: "روزانہ کا ہدف (8 گھنٹے)",
    status: "حیثیت",
    editRecord: "ریکارڈ میں ترمیم کریں",
    companyName: "Digital Nexus Solutions",
    adminDashboard: "سبسکرپشن کا انتظام",
    activeSubscriptions: "فعال سبسکرپشنز",
    newSubscription: "نئی سبسکرپشن",
    fullName: "پورا نام",
    nif: "ٹیکس آئی ڈی",
    email: "ای میل",
    phone: "فون",
    hourlyRate: "فی گھنٹہ کی شرح",
    createAccount: "اکاؤنٹ بنائیں",
    noUsers: "کوئی صارف رجسٹرڈ نہیں ہے۔",
    id: "آئی ڈی",
    actions: "عمل",
    editUser: "صارف میں ترمیم کریں",
    deleteUser: "حذف کریں",
    confirmDelete: "کیا آپ واقعی اس صارف کو حذف کرنا چاہتے ہیں؟",
    generatedId: "تخلیق کردہ آئی ڈی",
    changePassword: "پاس ورڈ تبدیل کریں",
    newPassword: "نیا پاس ورڈ",
    confirmPassword: "پاس ورڈ کی تصدیق کریں",
    passwordMismatch: "پاس ورڈ مماثل نہیں ہیں",
    provisionalPasswordNotice: "آپ ایک عارضی پاس ورڈ استعمال کر رہے ہیں۔ براہ کرم نیا پاس ورڈ سیٹ کریں۔",
    resetPassword: "پاس ورڈ دوبارہ ترتیب دیں (123)",
    passwordResetSuccess: "پاس ورڈ کامیابی کے ساتھ '123' پر دوبارہ ترتیب دیا گیا۔",
    socialSecurity: "سوشل سیکیورٹی",
    irs: "انکم ٹیکس",
    socialSecurityManual: "سوشل سیکیورٹی (دستی)",
    advance: "ایڈوانس",
    advancesReceived: "ایڈوانس وصول کیے گئے",
    totalAdvances: "کل ایڈوانس",
    deductionType: "کٹوتی کی قسم",
    percentage: "فیصد (%)",
    fixedValue: "مقررہ قیمت",
    value: "قیمت",
    netEarnings: "خالص آمدنی",
    grossEarnings: "مجموعی آمدنی",
    profileSettings: "پروفائل کی ترتیبات",
    updateProfile: "پروفائل کو اپ ڈیٹ کریں",
    profileUpdated: "پروفائل کامیابی کے ساتھ اپ ڈیٹ ہو گیا!",
    uploadPhoto: "تصویر اپ لوڈ کریں",
    removePhoto: "تصویر ہٹائیں",
    photoDescription: "اپنی پروفائل کو اپنی مرضی کے مطابق بنانے کے لیے اپنی ایک تصویر اپ لوڈ کریں۔",
    typeMessage: "ایک پیغام لکھیں...",
    send: "بھیجیں",
    noMessages: "ابھی تک کوئی پیغام نہیں ہے۔ ہیلو کہو!",
    country: "ملک",
    holiday: "چھٹی",
    totalDays: "کام کے دن",
    helpTitle: "ہم آپ کی کس طرح مدد کر سکتے ہیں؟",
    helpSubtitle: "ہمارے ڈیجیٹل اسسٹنٹ Axis سے پوچھیں",
    contactSupport: "انسانی مدد سے رابطہ کریں",
    botPlaceholder: "مثال: میں پی ڈی ایف کیسے برآمد کروں؟",
    ticketCreated: "آپ کی درخواست تکنیکی مدد کو بھیج دی گئی ہے۔ ہم جلد ہی آپ سے رابطہ کریں گے۔",
    botName: "Axis",
    helpWelcome: "ہیلو! میں Axis ہوں، آپ کا معاون۔ آپ اپنی زبان میں لکھ سکتے ہیں — میں ان سب کو سمجھتا ہوں۔ میں آپ کی کس طرح مدد کر سکتا ہوں؟",
    joinDiscount: "رعایت کے ساتھ شامل ہوں!",
    alreadyActive: "پہلے سے ہی فعال! لاگ ان کریں",
    salesPageTitle: "اپنا ڈیجیٹل نیکسس اکاؤنٹ فعال کریں",
    planMonthly: "ماہانہ منصوبہ - مکمل رسائی",
    paymentMethod: "ادائیگی کا طریقہ",
    mbway: "MBWAY",
    creditCard: "کریڈٹ کارڈ",
    cardNumber: "کارڈ نمبر",
    expiryDate: "میعاد ختم ہونے کی تاریخ (MM/YY)",
    cvv: "CVV",
    payAndActivate: "ادائیگی اور اکاؤنٹ کو فعال کریں",
    processingPayment: "ادائیگی پر کارروائی ہو رہی ہے...",
    paymentSuccess: "ادائیگی کی تصدیق ہو گئی! آپ کا اکاؤنٹ بن گیا ہے۔",
    mbwayNumber: "MBWAY موبائل نمبر",
    planYearly: "فی سال صرف 1 ادائیگی",
    unlimitedAccess: "لامحدود رسائی",
    memberChat: "ممبر چیٹ",
    continueToPayment: "ادائیگی جاری رکھیں",
    back: "واپس",
    limitedOfferApplied: "محدود پیشکش لاگو کی گئی",
    totalToday: "آج کل",
    perYear: "/سال",
    exportFeatures: "PDF/Excel برآمد کریں",
    support247: "24/7 سپورٹ",
    backupData: "بیک اپ ڈیٹا",
    backupSuccess: "بیک اپ کامیابی سے ڈاؤن لوڈ ہو گیا!",
    restoreBackup: "بیک اپ بحال کریں",
    restoreSuccess: "ڈیٹا کامیابی سے بحال کیا گیا!",
    invalidBackupFile: "غلط بیک اپ فائل.",
    workSite: "مقام/ورک سائٹ",
    observations: "مشاہدات"
  },
  ar: {
    welcome: "أهلاً بك",
    goodMorning: "صباح الخير",
    goodAfternoon: "مساء الخير",
    goodEvening: "مساء الخير",
    login: "تسجيل الدخول",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    dashboard: "لوحة القيادة",
    reports: "التقارير",
    profile: "الملف الشخصي",
    chat: "الدردشة / الشبكة",
    help: "مساعدة",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    clockIn: "تسجيل الدخول",
    clockOut: "تسجيل الخروج",
    date: "التاريخ",
    startTime: "وقت البدء",
    endTime: "وقت الانتهاء",
    lunch: "الغداء (دقيقة)",
    notes: "ملاحظات",
    save: "حفظ",
    cancel: "إلغاء",
    absent: "تسجيل غياب",
    present: "حاضر",
    totalHours: "إجمالي الساعات",
    expectedHours: "الساعات المتوقعة",
    balance: "الرصيد",
    exportPDF: "تصدير PDF",
    exportExcel: "تصدير Excel",
    mon: "الاثنين",
    tue: "الثلاثاء",
    wed: "الأربعاء",
    thu: "الخميس",
    fri: "الجمعة",
    sat: "السبت",
    sun: "الأحد",
    hoursWorked: "ساعات العمل",
    dailyGoal: "الهدف اليومي (8 ساعات)",
    status: "الحالة",
    editRecord: "تعديل السجل",
    companyName: "Digital Nexus Solutions",
    adminDashboard: "إدارة الاشتراكات",
    activeSubscriptions: "الاشتراكات النشطة",
    newSubscription: "اشتراك جديد",
    fullName: "الاسم الكامل",
    nif: "الرقم الضريبي",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    hourlyRate: "سعر الساعة",
    createAccount: "إنشاء حساب",
    noUsers: "لا يوجد مستخدمين مسجلين.",
    id: "المعرف",
    actions: "إجراءات",
    editUser: "تعديل المستخدم",
    deleteUser: "حذف",
    confirmDelete: "هل أنت متأكد أنك تريد حذف هذا المستخدم؟",
    generatedId: "المعرف المولد",
    changePassword: "تغيير كلمة المرور",
    newPassword: "كلمة المرور الجديدة",
    confirmPassword: "تأكيد كلمة المرور",
    passwordMismatch: "كلمات المرور غير متطابقة",
    provisionalPasswordNotice: "أنت تستخدم كلمة مرور مؤقتة. يرجى تعيين كلمة مرور جديدة.",
    resetPassword: "إعادة تعيين كلمة المرور (123)",
    passwordResetSuccess: "تم إعادة تعيين كلمة المرور إلى '123' بنجاح.",
    socialSecurity: "الضمان الاجتماعي",
    irs: "ضريبة الدخل",
    socialSecurityManual: "الضمان الاجتماعي (يدوي)",
    advance: "سلفة",
    advancesReceived: "السلف المستلمة",
    totalAdvances: "إجمالي السلف",
    deductionType: "نوع الخصم",
    percentage: "النسبة المئوية (%)",
    fixedValue: "قيمة ثابتة",
    value: "القيمة",
    netEarnings: "صافي الدخل",
    grossEarnings: "إجمالي الدخل",
    profileSettings: "إعدادات الملف الشخصي",
    updateProfile: "تحديث الملف الشخصي",
    profileUpdated: "تم تحديث الملف الشخصي بنجاح!",
    uploadPhoto: "تحميل الصورة",
    removePhoto: "إزالة الصورة",
    photoDescription: "قم بتحميل صورة لنفسك لتخصيص ملف التعريف الخاص بك.",
    typeMessage: "أكتب رسالة...",
    send: "إرسال",
    noMessages: "لا توجد رسائل بعد. قل مرحبا!",
    country: "البلد",
    holiday: "عطلة",
    totalDays: "أيام العمل",
    helpTitle: "كيف يمكننا مساعدتك؟",
    helpSubtitle: "اسأل Axis، مساعدنا الرقمي",
    contactSupport: "الاتصال بالدعم البشري",
    botPlaceholder: "مثال: كيف أقوم بتصدير PDF؟",
    ticketCreated: "تم إرسال طلبك إلى الدعم الفني. سوف نتصل بك قريبا.",
    botName: "Axis",
    helpWelcome: "مرحبًا! أنا Axis، مساعدك. يمكنك الكتابة بلغتك — أنا أفهم جميع اللغات. كيف يمكنني مساعدتك؟",
    joinDiscount: "انضم مع خصم!",
    alreadyActive: "نشط بالفعل! تسجيل الدخول",
    salesPageTitle: "تفعيل حساب Digital Nexus الخاص بك",
    planMonthly: "الخطة الشهرية - وصول كامل",
    paymentMethod: "طريقة الدفع",
    mbway: "MBWAY",
    creditCard: "بطاقة الائتمان",
    cardNumber: "رقم البطاقة",
    expiryDate: "تاريخ الانتهاء (MM/YY)",
    cvv: "CVV",
    payAndActivate: "الدفع وتفعيل الحساب",
    processingPayment: "جاري معالجة الدفع...",
    paymentSuccess: "تم تأكيد الدفع! تم إنشاء حسابك.",
    mbwayNumber: "رقم جوال MBWAY",
    planYearly: "دفعة واحدة فقط في السنة",
    unlimitedAccess: "وصول غير محدود",
    memberChat: "دردشة الأعضاء",
    continueToPayment: "متابعة للدفع",
    back: "رجوع",
    limitedOfferApplied: "تم تطبيق عرض محدود",
    totalToday: "المجموع اليوم",
    perYear: "/سنة",
    exportFeatures: "تصدير PDF/Excel",
    support247: "دعم 24/7",
    backupData: "نسخ احتياطي للبيانات",
    backupSuccess: "تم تنزيل النسخة الاحتياطية بنجاح!",
    restoreBackup: "استعادة النسخة الاحتياطية",
    restoreSuccess: "تمت استعادة البيانات بنجاح!",
    invalidBackupFile: "ملف النسخ الاحتياطي غير صالح.",
    workSite: "الموقع/موقع العمل",
    observations: "ملاحظات"
  }
};